// <auto-generated />
using System;
using LeadRecovery.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeadRecovery.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LeadRecoveryDbContext))]
    [Migration("20260715170834_AddDashboardOperations")]
    partial class AddDashboardOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeadRecovery.Domain.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("actor_type");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_json");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("TenantId", "CreatedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_events_tenant_created");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("LeadRecovery.Domain.Automations.ScheduledAction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action_type");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset>("ScheduledForUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_scheduled_actions");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_scheduled_actions_tenant_id_id");

                    b.HasIndex("Status", "ScheduledForUtc")
                        .HasDatabaseName("ix_scheduled_actions_due");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_scheduled_actions_tenant_id_idempotency_key");

                    b.HasIndex("TenantId", "LeadId", "Status")
                        .HasDatabaseName("ix_scheduled_actions_tenant_lead_status");

                    b.ToTable("scheduled_actions", null, t =>
                        {
                            t.HasCheckConstraint("ck_scheduled_actions_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_scheduled_actions_status", "status in ('Pending', 'Running', 'Completed', 'Cancelled', 'Failed')");
                        });
                });

            modelBuilder.Entity("LeadRecovery.Domain.Conversations.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_conversations");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_conversations_tenant_id_id");

                    b.HasIndex("TenantId", "LeadId", "CreatedAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_conversations_tenant_lead_created");

                    b.ToTable("conversations", null, t =>
                        {
                            t.HasCheckConstraint("ck_conversations_channel", "channel in ('Sms')");

                            t.HasCheckConstraint("ck_conversations_status", "status in ('Open', 'Closed')");
                        });
                });

            modelBuilder.Entity("LeadRecovery.Domain.Conversations.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("character varying(1600)")
                        .HasColumnName("body");

                    b.Property<string>("ClientIdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client_idempotency_key");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at_utc");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("direction");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("failure_code");

                    b.Property<string>("FailureDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_description");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderMessageSid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_message_sid");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at_utc");

                    b.Property<Guid?>("SentByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("sent_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_messages_tenant_id_id");

                    b.HasIndex("Provider", "ProviderMessageSid")
                        .IsUnique()
                        .HasDatabaseName("ux_messages_provider_sid")
                        .HasFilter("provider_message_sid is not null");

                    b.HasIndex("TenantId", "ClientIdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_messages_tenant_id_client_idempotency_key");

                    b.HasIndex("TenantId", "LeadId");

                    b.HasIndex("TenantId", "TemplateId");

                    b.HasIndex("TenantId", "ConversationId", "CreatedAtUtc")
                        .HasDatabaseName("ix_messages_tenant_conversation_created");

                    b.ToTable("messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_messages_direction", "direction in ('Inbound', 'Outbound')");

                            t.HasCheckConstraint("ck_messages_kind", "kind in ('Automated', 'Manual', 'System')");

                            t.HasCheckConstraint("ck_messages_status", "status in ('Queued', 'Sent', 'Delivered', 'Failed', 'Received', 'Suppressed')");
                        });
                });

            modelBuilder.Entity("LeadRecovery.Domain.Conversations.MessageTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1600)
                        .HasColumnType("character varying(1600)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("purpose");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_message_templates");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_message_templates_tenant_id_id");

                    b.HasIndex("TenantId", "Purpose")
                        .IsUnique()
                        .HasDatabaseName("ux_message_templates_tenant_purpose_active")
                        .HasFilter("is_active");

                    b.ToTable("message_templates", (string)null);
                });

            modelBuilder.Entity("LeadRecovery.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("OptedOutAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opted_out_at_utc");

                    b.Property<string>("PhoneE164")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("phone_e164");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("postal_code");

                    b.Property<string>("SmsConsentBasis")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sms_consent_basis");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_customers_tenant_id_id");

                    b.HasIndex("TenantId", "PhoneE164")
                        .IsUnique()
                        .HasDatabaseName("ux_customers_tenant_id_phone_e164");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("LeadRecovery.Domain.Identity.TenantMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_memberships");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_tenant_memberships_tenant_id_id");

                    b.HasAlternateKey("TenantId", "UserId")
                        .HasName("ak_tenant_memberships_tenant_id_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tenant_memberships_user_id");

                    b.ToTable("tenant_memberships", null, t =>
                        {
                            t.HasCheckConstraint("ck_tenant_memberships_role", "role in ('Owner', 'Manager', 'Staff', 'ReadOnly')");
                        });
                });

            modelBuilder.Entity("LeadRecovery.Domain.Integrations.ExternalEventReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_event_id");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("payload_hash");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("ProcessingResult")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("processing_result");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_external_event_receipts");

                    b.HasIndex("ReceivedAtUtc")
                        .HasDatabaseName("ix_external_event_receipts_received_at");

                    b.HasIndex("TenantId");

                    b.HasIndex("Provider", "EventType", "ExternalEventId")
                        .IsUnique()
                        .HasDatabaseName("ux_external_event_receipts_provider_event_identity");

                    b.ToTable("external_event_receipts", (string)null);
                });

            modelBuilder.Entity("LeadRecovery.Domain.Leads.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_user_id");

                    b.Property<string>("AutomationState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("automation_state");

                    b.Property<DateTimeOffset?>("BookedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booked_at_utc");

                    b.Property<string>("CloseReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("close_reason");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("LastBusinessActivityAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_business_activity_at_utc");

                    b.Property<DateTimeOffset?>("LastCustomerActivityAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_customer_activity_at_utc");

                    b.Property<string>("PrimaryPhoneE164")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("primary_phone_e164");

                    b.Property<Guid?>("ServiceCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_category_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("urgency");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_leads");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_leads_tenant_id_id");

                    b.HasIndex("TenantId", "CustomerId");

                    b.HasIndex("TenantId", "AssignedUserId", "Status")
                        .HasDatabaseName("ix_leads_tenant_assigned_status");

                    b.HasIndex("TenantId", "PrimaryPhoneE164", "CreatedAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_leads_tenant_phone_created");

                    b.HasIndex("TenantId", "Status", "CreatedAtUtc")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_leads_tenant_status_created");

                    b.HasIndex("TenantId", "Urgency", "Status")
                        .HasDatabaseName("ix_leads_tenant_urgency_status");

                    b.ToTable("leads", null, t =>
                        {
                            t.HasCheckConstraint("ck_leads_automation_state", "automation_state in ('Active', 'PausedByUser', 'PausedBySystem', 'Completed', 'SuppressedOptOut', 'SuppressedPolicy')");

                            t.HasCheckConstraint("ck_leads_source", "source in ('MissedCall', 'InboundSms', 'WebForm', 'Manual', 'Import')");

                            t.HasCheckConstraint("ck_leads_status", "status in ('New', 'Contacting', 'AwaitingCustomer', 'Qualified', 'BookingOffered', 'NeedsHuman', 'Booked', 'Closed', 'ClosedWon')");

                            t.HasCheckConstraint("ck_leads_urgency", "urgency in ('Unknown', 'Low', 'Normal', 'High', 'CriticalReview')");
                        });
                });

            modelBuilder.Entity("LeadRecovery.Domain.Leads.LeadNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_lead_notes");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_lead_notes_tenant_id_id");

                    b.HasIndex("TenantId", "AuthorUserId");

                    b.HasIndex("TenantId", "LeadId", "CreatedAtUtc")
                        .HasDatabaseName("ix_lead_notes_tenant_lead_created");

                    b.ToTable("lead_notes", (string)null);
                });

            modelBuilder.Entity("LeadRecovery.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutomationEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("automation_enabled");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("TimezoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ux_tenants_slug");

                    b.ToTable("tenants", null, t =>
                        {
                            t.HasCheckConstraint("ck_tenants_status", "status in ('Trial', 'Active', 'Suspended', 'Closed')");
                        });
                });

            modelBuilder.Entity("LeadRecovery.Domain.Tenancy.TenantPhoneNumber", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("InboundSmsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("inbound_sms_enabled");

                    b.Property<int>("InitialDelaySeconds")
                        .HasColumnType("integer")
                        .HasColumnName("initial_delay_seconds");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<bool>("MissedCallRecoveryEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("missed_call_recovery_enabled");

                    b.Property<string>("PhoneNumberE164")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("phone_number_e164");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderNumberSid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_number_sid");

                    b.PrimitiveCollection<string[]>("RecoverableCallStatuses")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("recoverable_call_statuses");

                    b.Property<int>("RecoveryCooldownSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("recovery_cooldown_seconds");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_phone_numbers");

                    b.HasAlternateKey("TenantId", "Id")
                        .HasName("ak_tenant_phone_numbers_tenant_id_id");

                    b.HasIndex("Provider", "PhoneNumberE164")
                        .IsUnique()
                        .HasDatabaseName("ux_tenant_phone_numbers_provider_phone_number");

                    b.HasIndex("Provider", "ProviderNumberSid")
                        .IsUnique()
                        .HasDatabaseName("ux_tenant_phone_numbers_provider_number_sid");

                    b.HasIndex("TenantId", "PhoneNumberE164")
                        .IsUnique()
                        .HasDatabaseName("ux_tenant_phone_numbers_tenant_phone_number");

                    b.ToTable("tenant_phone_numbers", null, t =>
                        {
                            t.HasCheckConstraint("ck_tenant_phone_numbers_initial_delay_seconds", "initial_delay_seconds between 0 and 3600");

                            t.HasCheckConstraint("ck_tenant_phone_numbers_recoverable_statuses", "cardinality(recoverable_call_statuses) > 0");

                            t.HasCheckConstraint("ck_tenant_phone_numbers_recovery_cooldown_seconds", "recovery_cooldown_seconds between 1 and 86400");
                        });
                });

            modelBuilder.Entity("LeadRecovery.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_user_name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("LeadRecovery.Domain.Audit.AuditEvent", b =>
                {
                    b.HasOne("LeadRecovery.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_events_tenants_tenant_id");
                });

            modelBuilder.Entity("LeadRecovery.Domain.Automations.ScheduledAction", b =>
                {
                    b.HasOne("LeadRecovery.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_scheduled_actions_tenants_tenant_id");

                    b.HasOne("LeadRecovery.Domain.Leads.Lead", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LeadId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_scheduled_actions_leads_tenant_id_lead_id");
                });

            modelBuilder.Entity("LeadRecovery.Domain.Conversations.Conversation", b =>
                {
                    b.HasOne("LeadRecovery.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_tenants_tenant_id");

                    b.HasOne("LeadRecovery.Domain.Leads.Lead", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LeadId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversations_leads_tenant_id_lead_id");
                });

            modelBuilder.Entity("LeadRecovery.Domain.Conversations.Message", b =>
                {
                    b.HasOne("LeadRecovery.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_tenants_tenant_id");

                    b.HasOne("LeadRecovery.Domain.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ConversationId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_conversations_tenant_id_conversation_id");

                    b.HasOne("LeadRecovery.Domain.Leads.Lead", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LeadId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_messages_leads_tenant_id_lead_id");

                    b.HasOne("LeadRecovery.Domain.Conversations.MessageTemplate", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "TemplateId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_messages_templates_tenant_id_template_id");
                });

            modelBuilder.Entity("LeadRecovery.Domain.Conversations.MessageTemplate", b =>
                {
                    b.HasOne("LeadRecovery.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_templates_tenants_tenant_id");
                });

            modelBuilder.Entity("LeadRecovery.Domain.Customers.Customer", b =>
                {
                    b.HasOne("LeadRecovery.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customers_tenants_tenant_id");
                });

            modelBuilder.Entity("LeadRecovery.Domain.Identity.TenantMembership", b =>
                {
                    b.HasOne("LeadRecovery.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_memberships_tenants_tenant_id");

                    b.HasOne("LeadRecovery.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_memberships_users_user_id");
                });

            modelBuilder.Entity("LeadRecovery.Domain.Integrations.ExternalEventReceipt", b =>
                {
                    b.HasOne("LeadRecovery.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_external_event_receipts_tenants_tenant_id");
                });

            modelBuilder.Entity("LeadRecovery.Domain.Leads.Lead", b =>
                {
                    b.HasOne("LeadRecovery.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_leads_tenants_tenant_id");

                    b.HasOne("LeadRecovery.Domain.Identity.TenantMembership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AssignedUserId")
                        .HasPrincipalKey("TenantId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_leads_memberships_tenant_id_assigned_user_id");

                    b.HasOne("LeadRecovery.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CustomerId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_leads_customers_tenant_id_customer_id");
                });

            modelBuilder.Entity("LeadRecovery.Domain.Leads.LeadNote", b =>
                {
                    b.HasOne("LeadRecovery.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lead_notes_tenants_tenant_id");

                    b.HasOne("LeadRecovery.Domain.Identity.TenantMembership", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "AuthorUserId")
                        .HasPrincipalKey("TenantId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lead_notes_memberships_tenant_id_author_user_id");

                    b.HasOne("LeadRecovery.Domain.Leads.Lead", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "LeadId")
                        .HasPrincipalKey("TenantId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lead_notes_leads_tenant_id_lead_id");
                });

            modelBuilder.Entity("LeadRecovery.Domain.Tenancy.TenantPhoneNumber", b =>
                {
                    b.HasOne("LeadRecovery.Domain.Tenancy.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_phone_numbers_tenants_tenant_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("LeadRecovery.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("LeadRecovery.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("LeadRecovery.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
