apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: leadrecovery

commonLabels:
  app.kubernetes.io/part-of: leadrecovery

resources:
  - ../base/foundation
  - migration-job.yaml

images:
  - name: ghcr.io/yashraj-rathore/leadrecovery-api
    newTag: sha-replace-me
