-- Reference schema only. EF Core migrations are the implementation source of truth.

create table tenants (
    id uuid primary key,
    name text not null,
    slug text not null unique,
    timezone_id text not null,
    status text not null,
    automation_enabled boolean not null default false,
    version bigint not null default 0,
    created_at_utc timestamptz not null,
    updated_at_utc timestamptz not null
);

create table tenant_phone_numbers (
    id uuid primary key,
    tenant_id uuid not null references tenants(id),
    provider text not null,
    phone_number_e164 text not null,
    provider_number_sid text not null,
    inbound_sms_enabled boolean not null default true,
    missed_call_recovery_enabled boolean not null default true,
    is_primary boolean not null default false,
    recoverable_call_statuses text[] not null
        check (cardinality(recoverable_call_statuses) > 0),
    initial_delay_seconds integer not null
        check (initial_delay_seconds between 0 and 3600),
    recovery_cooldown_seconds integer not null
        check (recovery_cooldown_seconds between 1 and 86400),
    unique(provider, provider_number_sid),
    unique(provider, phone_number_e164),
    unique(tenant_id, phone_number_e164)
);

create table users (
    id uuid primary key,
    display_name varchar(200) not null,
    is_active boolean not null,
    created_at_utc timestamptz not null,
    user_name varchar(256) null,
    normalized_user_name varchar(256) null unique,
    email varchar(320) null,
    normalized_email varchar(320) null unique,
    email_confirmed boolean not null,
    password_hash text null,
    security_stamp text null,
    concurrency_stamp text null,
    phone_number varchar(32) null,
    phone_number_confirmed boolean not null,
    two_factor_enabled boolean not null,
    lockout_end timestamptz null,
    lockout_enabled boolean not null,
    access_failed_count integer not null
);

create table tenant_memberships (
    id uuid primary key,
    tenant_id uuid not null references tenants(id),
    user_id uuid not null references users(id),
    role varchar(32) not null
        check (role in ('Owner', 'Manager', 'Staff', 'ReadOnly')),
    created_at_utc timestamptz not null,
    unique(tenant_id, id),
    unique(tenant_id, user_id)
);

create index ix_tenant_memberships_user_id
    on tenant_memberships(user_id);

create table user_claims (
    id integer generated by default as identity primary key,
    user_id uuid not null references users(id) on delete cascade,
    claim_type varchar(256) null,
    claim_value varchar(1024) null
);

create index ix_user_claims_user_id on user_claims(user_id);

create table user_logins (
    login_provider varchar(128) not null,
    provider_key varchar(128) not null,
    provider_display_name varchar(256) null,
    user_id uuid not null references users(id) on delete cascade,
    primary key(login_provider, provider_key)
);

create index ix_user_logins_user_id on user_logins(user_id);

create table user_tokens (
    user_id uuid not null references users(id) on delete cascade,
    login_provider varchar(128) not null,
    name varchar(128) not null,
    value text null,
    primary key(user_id, login_provider, name)
);

create table customers (
    id uuid primary key,
    tenant_id uuid not null references tenants(id),
    phone_e164 varchar(16) not null,
    name varchar(200) null,
    email varchar(320) null,
    city varchar(100) null,
    postal_code varchar(20) null,
    sms_consent_basis varchar(100) null,
    opted_out_at_utc timestamptz null,
    created_at_utc timestamptz not null,
    unique(tenant_id, phone_e164),
    unique(tenant_id, id)
);

create table leads (
    id uuid primary key,
    tenant_id uuid not null references tenants(id),
    customer_id uuid null,
    primary_phone_e164 varchar(32) not null,
    display_name varchar(200) null,
    source varchar(32) not null,
    status varchar(32) not null,
    urgency varchar(32) not null,
    service_category_id uuid null,
    assigned_user_id uuid null,
    automation_state varchar(32) not null,
    last_customer_activity_at_utc timestamptz null,
    last_business_activity_at_utc timestamptz null,
    booked_at_utc timestamptz null,
    closed_at_utc timestamptz null,
    close_reason varchar(32) null,
    version bigint not null default 0,
    created_at_utc timestamptz not null,
    updated_at_utc timestamptz not null,
    unique(tenant_id, id),
    foreign key (tenant_id, customer_id) references customers(tenant_id, id),
    foreign key (tenant_id, assigned_user_id)
        references tenant_memberships(tenant_id, user_id)
);

create index ix_leads_tenant_status_created
    on leads(tenant_id, status, created_at_utc desc);
create index ix_leads_tenant_phone_created
    on leads(tenant_id, primary_phone_e164, created_at_utc desc);
create index ix_leads_tenant_assigned_status
    on leads(tenant_id, assigned_user_id, status);
create index ix_leads_tenant_urgency_status
    on leads(tenant_id, urgency, status);

create table lead_notes (
    id uuid primary key,
    tenant_id uuid not null references tenants(id),
    lead_id uuid not null,
    author_user_id uuid not null,
    body varchar(2000) not null,
    created_at_utc timestamptz not null,
    unique(tenant_id, id),
    foreign key (tenant_id, lead_id) references leads(tenant_id, id),
    foreign key (tenant_id, author_user_id)
        references tenant_memberships(tenant_id, user_id)
);

create index ix_lead_notes_tenant_lead_created
    on lead_notes(tenant_id, lead_id, created_at_utc);
create index ix_lead_notes_tenant_id_author_user_id
    on lead_notes(tenant_id, author_user_id);

create table conversations (
    id uuid primary key,
    tenant_id uuid not null references tenants(id),
    lead_id uuid not null,
    channel varchar(16) not null,
    status varchar(16) not null,
    created_at_utc timestamptz not null,
    closed_at_utc timestamptz null,
    unique(tenant_id, id),
    foreign key (tenant_id, lead_id) references leads(tenant_id, id)
);

create index ix_conversations_tenant_lead_created
    on conversations(tenant_id, lead_id, created_at_utc desc);

create table message_templates (
    id uuid primary key,
    tenant_id uuid not null references tenants(id),
    name varchar(120) not null,
    purpose varchar(80) not null,
    body varchar(1600) not null,
    version integer not null,
    is_approved boolean not null,
    is_active boolean not null,
    created_by_user_id uuid not null,
    approved_by_user_id uuid null,
    created_at_utc timestamptz not null,
    approved_at_utc timestamptz null,
    unique(tenant_id, id)
);

create unique index ux_message_templates_tenant_purpose_active
    on message_templates(tenant_id, purpose)
    where is_active;

create table workflow_definitions (
    id uuid primary key,
    tenant_id uuid not null references tenants(id) on delete cascade,
    name varchar(120) not null,
    version integer not null,
    is_active boolean not null,
    booking_url varchar(2048) not null,
    follow_up_policy_json jsonb not null,
    business_hours_policy_json jsonb not null,
    qualification_policy_json jsonb not null,
    created_at_utc timestamptz not null,
    updated_at_utc timestamptz not null,
    unique(tenant_id, id),
    unique(tenant_id, version)
);

create unique index ux_workflow_definitions_tenant_active
    on workflow_definitions(tenant_id)
    where is_active;

create table messages (
    id uuid primary key,
    tenant_id uuid not null references tenants(id),
    lead_id uuid not null,
    conversation_id uuid not null,
    direction varchar(16) not null,
    kind varchar(16) not null,
    provider varchar(50) not null,
    provider_message_sid varchar(100) null,
    client_idempotency_key varchar(200) not null,
    body varchar(1600) not null,
    status varchar(16) not null,
    failure_code varchar(100) null,
    failure_description varchar(500) null,
    sent_by_user_id uuid null,
    template_id uuid null,
    created_at_utc timestamptz not null,
    sent_at_utc timestamptz null,
    delivered_at_utc timestamptz null,
    unique(tenant_id, client_idempotency_key),
    unique(tenant_id, id),
    foreign key (tenant_id, lead_id) references leads(tenant_id, id),
    foreign key (tenant_id, conversation_id) references conversations(tenant_id, id),
    foreign key (tenant_id, template_id) references message_templates(tenant_id, id)
);

create unique index ux_messages_provider_sid
    on messages(provider, provider_message_sid)
    where provider_message_sid is not null;

create index ix_messages_tenant_conversation_created
    on messages(tenant_id, conversation_id, created_at_utc);

create table qualification_answers (
    id uuid primary key,
    tenant_id uuid not null references tenants(id) on delete cascade,
    lead_id uuid not null,
    source_message_id uuid not null,
    question_key varchar(80) not null,
    value varchar(500) null,
    outcome varchar(16) not null
        check (outcome in ('Accepted', 'Unknown', 'Ambiguous')),
    created_at_utc timestamptz not null,
    unique(tenant_id, id),
    unique(tenant_id, lead_id, question_key),
    unique(tenant_id, source_message_id),
    foreign key (tenant_id, lead_id)
        references leads(tenant_id, id) on delete cascade,
    foreign key (tenant_id, source_message_id)
        references messages(tenant_id, id)
);

create table ai_analyses (
    id uuid primary key,
    tenant_id uuid not null references tenants(id) on delete cascade,
    lead_id uuid not null,
    schema_version varchar(20) not null,
    provider varchar(50) not null,
    model_reference varchar(200) not null,
    input_hash char(64) not null,
    allowed_categories_json jsonb not null,
    category_suggestion varchar(100) not null,
    urgency_suggestion varchar(32) not null
        check (urgency_suggestion in ('Unknown', 'Low', 'Normal', 'High', 'CriticalReview')),
    summary varchar(1000) not null,
    extracted_city varchar(200) null,
    extracted_postal_code varchar(200) null,
    extracted_preferred_callback_window varchar(200) null,
    suggested_reply varchar(1000) null,
    confidence double precision not null check (confidence >= 0 and confidence <= 1),
    requires_human_review boolean not null,
    reason_codes_json jsonb not null,
    raw_structured_output_json jsonb not null,
    review_status varchar(16) not null
        check (review_status in ('Pending', 'Accepted', 'Edited', 'Rejected')),
    reviewed_category varchar(100) null,
    reviewed_urgency varchar(32) null
        check (reviewed_urgency is null or reviewed_urgency in ('Unknown', 'Low', 'Normal', 'High', 'CriticalReview')),
    reviewed_summary varchar(1000) null,
    reviewed_city varchar(200) null,
    reviewed_postal_code varchar(200) null,
    reviewed_preferred_callback_window varchar(200) null,
    reviewed_suggested_reply varchar(1000) null,
    correction_reason varchar(500) null,
    reviewed_by_user_id uuid null,
    reviewed_at_utc timestamptz null,
    version bigint not null default 0,
    created_at_utc timestamptz not null,
    unique(tenant_id, id),
    unique(tenant_id, lead_id, schema_version, input_hash),
    foreign key (tenant_id, lead_id)
        references leads(tenant_id, id) on delete cascade,
    foreign key (tenant_id, reviewed_by_user_id)
        references tenant_memberships(tenant_id, user_id),
    check (
        (review_status = 'Pending' and reviewed_by_user_id is null and reviewed_at_utc is null)
        or
        (review_status <> 'Pending' and reviewed_by_user_id is not null and reviewed_at_utc is not null)
    ),
    check (
        (review_status in ('Accepted', 'Edited') and reviewed_category is not null and reviewed_urgency is not null and reviewed_summary is not null)
        or
        (review_status in ('Pending', 'Rejected') and reviewed_category is null and reviewed_urgency is null and reviewed_summary is null)
    )
);

create index ix_ai_analyses_tenant_lead_review_created
    on ai_analyses(tenant_id, lead_id, review_status, created_at_utc);

create index ix_ai_analyses_tenant_reviewer
    on ai_analyses(tenant_id, reviewed_by_user_id);

create table external_event_receipts (
    id uuid primary key,
    tenant_id uuid null references tenants(id),
    provider varchar(50) not null,
    event_type varchar(100) not null,
    external_event_id varchar(200) not null,
    payload_hash varchar(128) not null,
    received_at_utc timestamptz not null,
    processed_at_utc timestamptz null,
    processing_result varchar(500) null,
    unique(provider, event_type, external_event_id)
);

create index ix_external_event_receipts_received_at
    on external_event_receipts(received_at_utc);

create table scheduled_actions (
    id uuid primary key,
    tenant_id uuid not null references tenants(id),
    lead_id uuid not null,
    action_type varchar(100) not null,
    scheduled_for_utc timestamptz not null,
    status varchar(16) not null
        check (status in ('Pending', 'Running', 'Completed', 'Cancelled', 'Failed')),
    attempt_count integer not null default 0 check (attempt_count >= 0),
    idempotency_key varchar(200) not null,
    payload_json jsonb not null,
    last_error varchar(1000) null,
    correlation_id varchar(100) null,
    trace_parent varchar(55) null,
    trace_state varchar(512) null,
    created_at_utc timestamptz not null,
    updated_at_utc timestamptz not null,
    unique(tenant_id, idempotency_key),
    unique(tenant_id, id),
    foreign key (tenant_id, lead_id) references leads(tenant_id, id)
);

create index ix_scheduled_actions_due
    on scheduled_actions(status, scheduled_for_utc);

create index ix_scheduled_actions_tenant_lead_status
    on scheduled_actions(tenant_id, lead_id, status);

create table audit_events (
    id uuid primary key,
    tenant_id uuid null references tenants(id),
    actor_type text not null,
    actor_id text null,
    action text not null,
    entity_type text not null,
    entity_id text not null,
    before_json jsonb null,
    after_json jsonb null,
    correlation_id text not null,
    created_at_utc timestamptz not null
);

create index ix_audit_events_tenant_created
    on audit_events(tenant_id, created_at_utc desc);
