apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: leadrecovery-local

resources:
  - ../../migration

images:
  - name: ghcr.io/yashraj-rathore/leadrecovery-api
    newName: leadrecovery-api
    newTag: local

patches:
  - target:
      kind: Namespace
      name: leadrecovery
    patch: |-
      - op: replace
        path: /metadata/name
        value: leadrecovery-local
  - target:
      kind: ConfigMap
      name: leadrecovery-config
    patch: |-
      - op: replace
        path: /data/ASPNETCORE_ENVIRONMENT
        value: Development
      - op: replace
        path: /data/SERVER_API_BASE_URL
        value: http://leadrecovery-api:8080
      - op: replace
        path: /data/TWILIO_WEBHOOK_BASE_URL
        value: http://leadrecovery.local
